/**
 * Configuration des Server Actions disponibles pour le système de permissions
 * 
 * Cette liste prédéfinie permet à l'administrateur de sélectionner facilement
 * les actions sans avoir à connaître leurs noms exacts.
 */

export interface ServerActionConfig {
  action: string; // Nom de la Server Action
  label: string; // Libellé affiché à l'utilisateur
  description: string; // Description de ce que fait l'action
  resource: string; // Ressource concernée
  defaultType: "READ" | "WRITE" | "DELETE" | "MANAGE"; // Type de permission par défaut
  route?: string; // Route associée (optionnel)
  category: string; // Catégorie pour regrouper les actions
}

export const SERVER_ACTIONS_CONFIG: ServerActionConfig[] = [
  // ========== FINANCES ==========
  {
    action: "getAllDettesInitiales",
    label: "Lister les dettes initiales",
    description: "Afficher la liste de toutes les dettes initiales des adhérents",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances/dettes",
    category: "Finances",
  },
  {
    action: "getDetteInitialeById",
    label: "Consulter une dette initiale",
    description: "Voir les détails d'une dette initiale spécifique",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances/dettes",
    category: "Finances",
  },
  {
    action: "createDetteInitiale",
    label: "Créer une dette initiale",
    description: "Créer une nouvelle dette initiale pour un adhérent",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/dettes",
    category: "Finances",
  },
  {
    action: "updateDetteInitiale",
    label: "Modifier une dette initiale",
    description: "Modifier une dette initiale existante",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/dettes",
    category: "Finances",
  },
  {
    action: "getAllPaiements",
    label: "Lister les paiements",
    description: "Afficher la liste de tous les paiements effectués",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "createPaiementGeneral",
    label: "Enregistrer un paiement",
    description: "Enregistrer un nouveau paiement pour un adhérent",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "createPaiement",
    label: "Enregistrer un paiement (cotisation)",
    description: "Enregistrer un paiement en espèces sur une cotisation mensuelle",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "uploadJustificatifPaiement",
    label: "Téléverser un justificatif de virement",
    description: "Upload d'un justificatif pour valider un paiement par virement",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "getCotisationsMensuellesByPeriode",
    label: "Lister les cotisations du mois (paiements)",
    description: "Afficher les cotisations mensuelles pour la période (page Paiements)",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "updatePaiement",
    label: "Modifier un paiement",
    description: "Corriger les erreurs de saisie d'un paiement enregistré",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "getAllAssistances",
    label: "Lister les assistances",
    description: "Afficher la liste de toutes les assistances",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances/assistances",
    category: "Finances",
  },
  {
    action: "createAssistance",
    label: "Créer une assistance",
    description: "Créer une nouvelle assistance pour un adhérent",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/assistances",
    category: "Finances",
  },
  {
    action: "updateAssistance",
    label: "Modifier une assistance",
    description: "Modifier une assistance existante",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/assistances",
    category: "Finances",
  },
  {
    action: "deleteAssistance",
    label: "Supprimer une assistance",
    description: "Supprimer une assistance (si non affectée ou payée)",
    resource: "finances",
    defaultType: "DELETE",
    route: "/admin/finances/assistances",
    category: "Finances",
  },
  {
    action: "affecterAssistanceToCotisationDuMois",
    label: "Affecter une assistance à la cotisation du mois",
    description: "Lier une assistance à une cotisation mensuelle pour une période donnée",
    resource: "finances",
    defaultType: "WRITE",
    route: "/admin/finances/assistances",
    category: "Finances",
  },
  {
    action: "getAllPaiements",
    label: "Lister les paiements / Historique des paiements",
    description: "Afficher la liste de tous les paiements effectués",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances/paiements",
    category: "Finances",
  },
  {
    action: "getFinancialStats",
    label: "Voir les statistiques financières",
    description: "Consulter les statistiques et indicateurs financiers",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances",
    category: "Finances",
  },
  {
    action: "getAdherentFinancialItems",
    label: "Voir les éléments financiers d'un adhérent",
    description: "Consulter les dettes, cotisations et assistances d'un adhérent",
    resource: "finances",
    defaultType: "READ",
    route: "/admin/finances",
    category: "Finances",
  },

  // ========== COTISATIONS ==========
  {
    action: "getAdherentsWithCotisations",
    label: "Lister les adhérents avec cotisations",
    description: "Afficher la liste des adhérents et leurs cotisations",
    resource: "cotisations",
    defaultType: "READ",
    route: "/admin/cotisations/gestion",
    category: "Cotisations",
  },
  {
    action: "createManualCotisation",
    label: "Créer une cotisation manuelle",
    description: "Créer une cotisation manuelle pour un adhérent",
    resource: "cotisations",
    defaultType: "WRITE",
    route: "/admin/cotisations/gestion",
    category: "Cotisations",
  },
  {
    action: "updateCotisation",
    label: "Modifier une cotisation",
    description: "Modifier une cotisation existante",
    resource: "cotisations",
    defaultType: "WRITE",
    route: "/admin/cotisations/gestion",
    category: "Cotisations",
  },
  {
    action: "getAllCotisationsDuMois",
    label: "Lister les cotisations du mois",
    description: "Afficher les cotisations mensuelles (affectations)",
    resource: "cotisations",
    defaultType: "READ",
    route: "/admin/cotisations-du-mois",
    category: "Cotisations",
  },
  {
    action: "getCotisationDuMoisById",
    label: "Consulter une cotisation du mois",
    description: "Voir le détail d'une cotisation mensuelle",
    resource: "cotisations",
    defaultType: "READ",
    route: "/admin/cotisations-du-mois",
    category: "Cotisations",
  },
  {
    action: "createCotisationDuMois",
    label: "Créer une cotisation du mois (affectation)",
    description: "Créer une ligne de cotisation mensuelle / affectation",
    resource: "cotisations",
    defaultType: "WRITE",
    route: "/admin/cotisations-du-mois",
    category: "Cotisations",
  },
  {
    action: "updateCotisationDuMois",
    label: "Modifier une cotisation du mois",
    description: "Modifier une cotisation mensuelle existante",
    resource: "cotisations",
    defaultType: "WRITE",
    route: "/admin/cotisations-du-mois",
    category: "Cotisations",
  },
  {
    action: "deleteCotisationDuMois",
    label: "Supprimer une cotisation du mois",
    description: "Supprimer une affectation / cotisation mensuelle",
    resource: "cotisations",
    defaultType: "DELETE",
    route: "/admin/cotisations-du-mois",
    category: "Cotisations",
  },

  // ========== DÉPENSES ==========
  {
    action: "getAllDepenses",
    label: "Lister les dépenses",
    description: "Afficher la liste de toutes les dépenses",
    resource: "depenses",
    defaultType: "READ",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "getDepenseStats",
    label: "Voir les statistiques des dépenses",
    description: "Consulter les statistiques et indicateurs des dépenses",
    resource: "depenses",
    defaultType: "READ",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "getDepenseById",
    label: "Consulter une dépense",
    description: "Voir les détails d'une dépense spécifique",
    resource: "depenses",
    defaultType: "READ",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "createDepense",
    label: "Créer une dépense",
    description: "Créer une nouvelle dépense",
    resource: "depenses",
    defaultType: "WRITE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "updateDepense",
    label: "Modifier une dépense",
    description: "Modifier une dépense existante",
    resource: "depenses",
    defaultType: "WRITE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "deleteDepense",
    label: "Supprimer une dépense",
    description: "Supprimer une dépense",
    resource: "depenses",
    defaultType: "DELETE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "validateDepense",
    label: "Valider une dépense",
    description: "Valider une dépense en attente",
    resource: "depenses",
    defaultType: "WRITE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "rejectDepense",
    label: "Rejeter une dépense",
    description: "Rejeter une dépense en attente",
    resource: "depenses",
    defaultType: "WRITE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "uploadJustificatif",
    label: "Ajouter un justificatif",
    description: "Uploader un justificatif (fichier) pour une dépense",
    resource: "depenses",
    defaultType: "WRITE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "deleteJustificatif",
    label: "Supprimer un justificatif",
    description: "Supprimer un justificatif d'une dépense",
    resource: "depenses",
    defaultType: "DELETE",
    route: "/admin/depenses",
    category: "Dépenses",
  },
  {
    action: "updateJustificatif",
    label: "Modifier un justificatif",
    description: "Modifier les métadonnées d'un justificatif (ex. nom du fichier)",
    resource: "depenses",
    defaultType: "WRITE",
    route: "/admin/depenses",
    category: "Dépenses",
  },

  // ========== EMAILS ==========
  {
    action: "sendEmails",
    label: "Envoi de mails",
    description: "Envoyer des emails aux adhérents (admin)",
    resource: "emails",
    defaultType: "WRITE",
    route: "/admin/emails",
    category: "Emails",
  },

  // ========== UTILISATEURS ==========
  {
    action: "getAllUsersForAdmin",
    label: "Lister les utilisateurs",
    description: "Afficher la liste de tous les utilisateurs",
    resource: "users",
    defaultType: "READ",
    route: "/admin/users",
    category: "Utilisateurs",
  },
  {
    action: "adminUpdateUserRole",
    label: "Modifier le rôle d'un utilisateur",
    description: "Changer le rôle d'un utilisateur",
    resource: "users",
    defaultType: "WRITE",
    route: "/admin/users",
    category: "Utilisateurs",
  },

  // ========== RAPPORTS DE RÉUNION ==========
  {
    action: "getAllRapportsReunion",
    label: "Lister les rapports de réunion",
    description: "Afficher la liste de tous les rapports de réunion",
    resource: "rapports",
    defaultType: "READ",
    route: "/admin/rapports-reunion",
    category: "Rapports",
  },
  {
    action: "createRapportReunion",
    label: "Créer un rapport de réunion",
    description: "Créer un nouveau rapport de réunion",
    resource: "rapports",
    defaultType: "WRITE",
    route: "/admin/rapports-reunion",
    category: "Rapports",
  },
  {
    action: "updateRapportReunion",
    label: "Modifier un rapport de réunion",
    description: "Modifier un rapport de réunion existant",
    resource: "rapports",
    defaultType: "WRITE",
    route: "/admin/rapports-reunion",
    category: "Rapports",
  },
  {
    action: "deleteRapportReunion",
    label: "Supprimer un rapport de réunion",
    description: "Supprimer un rapport de réunion",
    resource: "rapports",
    defaultType: "DELETE",
    route: "/admin/rapports-reunion",
    category: "Rapports",
  },

  // ========== RGPD ==========
  {
    action: "getAllDataDeletionRequests",
    label: "Lister les demandes RGPD",
    description: "Afficher la liste des demandes de suppression de données",
    resource: "rgpd",
    defaultType: "READ",
    route: "/admin/rgpd/demandes",
    category: "RGPD",
  },

  // ========== MENUS ==========
  {
    action: "getAllMenus",
    label: "Lister les menus",
    description: "Afficher la liste de tous les menus",
    resource: "menus",
    defaultType: "READ",
    route: "/admin/menus",
    category: "Menus",
  },
  {
    action: "createMenu",
    label: "Créer un menu",
    description: "Créer un nouveau menu",
    resource: "menus",
    defaultType: "WRITE",
    route: "/admin/menus",
    category: "Menus",
  },
  {
    action: "updateMenu",
    label: "Modifier un menu",
    description: "Modifier un menu existant",
    resource: "menus",
    defaultType: "WRITE",
    route: "/admin/menus",
    category: "Menus",
  },
  {
    action: "deleteMenu",
    label: "Supprimer un menu",
    description: "Supprimer un menu",
    resource: "menus",
    defaultType: "DELETE",
    route: "/admin/menus",
    category: "Menus",
  },

  // ========== DOCUMENTS ==========
  {
    action: "getAllDocuments",
    label: "Lister les documents (admin)",
    description: "Afficher la liste de tous les documents (vue admin)",
    resource: "documents",
    defaultType: "READ",
    route: "/admin/documents",
    category: "Documents",
  },
  {
    action: "adminUpdateDocument",
    label: "Modifier un document (admin)",
    description: "Mettre à jour les métadonnées d'un document (vue admin)",
    resource: "documents",
    defaultType: "WRITE",
    route: "/admin/documents",
    category: "Documents",
  },
  {
    action: "adminDeleteDocument",
    label: "Supprimer un document (admin)",
    description: "Supprimer un document (vue admin)",
    resource: "documents",
    defaultType: "DELETE",
    route: "/admin/documents",
    category: "Documents",
  },

  // ========== BOÎTE À IDÉES ==========
  {
    action: "getAllIdeesForAdmin",
    label: "Lister les idées (admin)",
    description: "Afficher la liste de toutes les idées (vue admin)",
    resource: "idees",
    defaultType: "READ",
    route: "/admin/idees",
    category: "Boîte à idées",
  },
  {
    action: "validerIdee",
    label: "Valider une idée",
    description: "Valider une idée soumise par un adhérent",
    resource: "idees",
    defaultType: "WRITE",
    route: "/admin/idees",
    category: "Boîte à idées",
  },
  {
    action: "rejeterIdee",
    label: "Rejeter une idée",
    description: "Rejeter une idée avec une raison",
    resource: "idees",
    defaultType: "WRITE",
    route: "/admin/idees",
    category: "Boîte à idées",
  },
  {
    action: "bloquerIdee",
    label: "Bloquer une idée",
    description: "Bloquer une idée avec une raison",
    resource: "idees",
    defaultType: "WRITE",
    route: "/admin/idees",
    category: "Boîte à idées",
  },
  {
    action: "supprimerCommentaire",
    label: "Supprimer un commentaire (admin)",
    description: "Supprimer (masquer) un commentaire d'idée avec une raison",
    resource: "idees",
    defaultType: "DELETE",
    route: "/admin/idees",
    category: "Boîte à idées",
  },

  // ========== PROJETS ==========
  {
    action: "getAllProjets",
    label: "Lister les projets",
    description: "Afficher la liste de tous les projets (admin)",
    resource: "projets",
    defaultType: "READ",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "getProjetById",
    label: "Consulter un projet",
    description: "Voir le détail d'un projet (admin)",
    resource: "projets",
    defaultType: "READ",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "createProjet",
    label: "Créer un projet",
    description: "Créer un nouveau projet",
    resource: "projets",
    defaultType: "WRITE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "updateProjet",
    label: "Modifier un projet",
    description: "Modifier un projet existant",
    resource: "projets",
    defaultType: "WRITE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "deleteProjet",
    label: "Supprimer un projet",
    description: "Supprimer un projet",
    resource: "projets",
    defaultType: "DELETE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "createSousProjet",
    label: "Créer une tâche",
    description: "Créer une tâche (sous-projet) dans un projet",
    resource: "projets",
    defaultType: "WRITE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "updateSousProjet",
    label: "Modifier une tâche",
    description: "Modifier une tâche (sous-projet) existante",
    resource: "projets",
    defaultType: "WRITE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "deleteSousProjet",
    label: "Supprimer une tâche",
    description: "Supprimer une tâche (sous-projet) d'un projet",
    resource: "projets",
    defaultType: "DELETE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "affecterSousProjet",
    label: "Affecter des adhérents à une tâche",
    description: "Affecter/retirer des adhérents sur une tâche (admin)",
    resource: "projets",
    defaultType: "MANAGE",
    route: "/admin/projets",
    category: "Projets",
  },
  {
    action: "retirerAffectation",
    label: "Retirer une affectation",
    description: "Retirer un adhérent d'une tâche (admin)",
    resource: "projets",
    defaultType: "MANAGE",
    route: "/admin/projets",
    category: "Projets",
  },

  // ========== ÉVÉNEMENTS ==========
  {
    action: "getAllEvenements",
    label: "Lister les événements (admin)",
    description: "Afficher la liste de tous les événements (vue admin)",
    resource: "evenements",
    defaultType: "READ",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "getEvenementById",
    label: "Consulter un événement",
    description: "Voir le détail d'un événement (admin)",
    resource: "evenements",
    defaultType: "READ",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "getEvenementsStats",
    label: "Voir les statistiques des événements",
    description: "Consulter les statistiques des événements",
    resource: "evenements",
    defaultType: "READ",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "createEvenement",
    label: "Créer un événement",
    description: "Créer un nouvel événement",
    resource: "evenements",
    defaultType: "WRITE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "updateEvenement",
    label: "Modifier un événement",
    description: "Modifier un événement existant",
    resource: "evenements",
    defaultType: "WRITE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "deleteEvenement",
    label: "Supprimer un événement",
    description: "Supprimer un événement",
    resource: "evenements",
    defaultType: "DELETE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "uploadEvenementImage",
    label: "Upload image événement",
    description: "Uploader une image pour un événement",
    resource: "evenements",
    defaultType: "WRITE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "sendEventInvitations",
    label: "Envoyer invitations événement",
    description: "Envoyer les invitations par email pour un événement",
    resource: "evenements",
    defaultType: "WRITE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "getAdherentsForEvent",
    label: "Lister adhérents pour événement",
    description: "Liste des adhérents (gestion participants / inscriptions)",
    resource: "evenements",
    defaultType: "READ",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "addParticipantToEvent",
    label: "Ajouter participant à un événement",
    description: "Ajouter un participant à un événement (admin)",
    resource: "evenements",
    defaultType: "WRITE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "removeParticipantFromEvent",
    label: "Retirer participant d'un événement",
    description: "Retirer un participant d'un événement (admin)",
    resource: "evenements",
    defaultType: "WRITE",
    route: "/admin/evenements",
    category: "Événements",
  },
  {
    action: "exportAllEvenementsCalendar",
    label: "Exporter calendrier événements",
    description: "Exporter tous les événements en format calendrier (admin)",
    resource: "evenements",
    defaultType: "READ",
    route: "/admin/evenements",
    category: "Événements",
  },

  // ========== GALERIE ==========
  {
    action: "getAllMediaGalerie",
    label: "Lister les médias de la galerie",
    description: "Afficher la liste des médias (admin)",
    resource: "galerie",
    defaultType: "READ",
    route: "/admin/galerie",
    category: "Galerie",
  },
  {
    action: "getMediaGalerieById",
    label: "Consulter un média galerie",
    description: "Voir le détail d'un média",
    resource: "galerie",
    defaultType: "READ",
    route: "/admin/galerie",
    category: "Galerie",
  },
  {
    action: "uploadMediaGalerie",
    label: "Ajouter un média à la galerie",
    description: "Uploader une image ou vidéo dans la galerie",
    resource: "galerie",
    defaultType: "WRITE",
    route: "/admin/galerie",
    category: "Galerie",
  },
  {
    action: "updateMediaGalerie",
    label: "Modifier un média galerie",
    description: "Modifier les métadonnées d'un média",
    resource: "galerie",
    defaultType: "WRITE",
    route: "/admin/galerie",
    category: "Galerie",
  },
  {
    action: "deleteMediaGalerie",
    label: "Supprimer un média galerie",
    description: "Supprimer un média de la galerie",
    resource: "galerie",
    defaultType: "DELETE",
    route: "/admin/galerie",
    category: "Galerie",
  },

  // ========== CHAT / MESSAGERIE ==========
  {
    action: "getUsersForConversation",
    label: "Lister utilisateurs pour conversation",
    description: "Liste des utilisateurs (création conversation admin / messagerie)",
    resource: "chat",
    defaultType: "READ",
    route: "/chat",
    category: "Chat",
  },
  {
    action: "getEvenementsForConversation",
    label: "Lister événements pour conversation",
    description: "Liste des événements (création conversation liée à un événement)",
    resource: "chat",
    defaultType: "READ",
    route: "/chat",
    category: "Chat",
  },

  // ========== EXPORTS ==========
  {
    action: "getAdherentsForExport",
    label: "Export adhérents",
    description: "Exporter la liste des adhérents",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getCotisationsForExport",
    label: "Export cotisations",
    description: "Exporter les cotisations",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getPaiementsForExport",
    label: "Export paiements",
    description: "Exporter les paiements",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getEvenementsForExport",
    label: "Export événements",
    description: "Exporter les événements",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getInscriptionsEvenementsForExport",
    label: "Export inscriptions événements",
    description: "Exporter les inscriptions aux événements",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getElectionsResultsForExport",
    label: "Export résultats élections",
    description: "Exporter les résultats des élections",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getDocumentsForExport",
    label: "Export documents",
    description: "Exporter les documents",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },
  {
    action: "getRelancesForExport",
    label: "Export relances",
    description: "Exporter les relances",
    resource: "exports",
    defaultType: "READ",
    route: "/admin/exports",
    category: "Exports",
  },

  // ========== RÉSERVATIONS ==========
  {
    action: "createRessource",
    label: "Créer une ressource",
    description: "Créer une ressource réservable",
    resource: "reservations",
    defaultType: "WRITE",
    route: "/admin/reservations",
    category: "Réservations",
  },
  {
    action: "getAllRessources",
    label: "Lister les ressources",
    description: "Afficher la liste des ressources (admin)",
    resource: "reservations",
    defaultType: "READ",
    route: "/admin/reservations",
    category: "Réservations",
  },
  {
    action: "createReservation",
    label: "Créer une réservation",
    description: "Créer une réservation (admin)",
    resource: "reservations",
    defaultType: "WRITE",
    route: "/admin/reservations",
    category: "Réservations",
  },
  {
    action: "getAllReservations",
    label: "Lister les réservations",
    description: "Afficher la liste des réservations",
    resource: "reservations",
    defaultType: "READ",
    route: "/admin/reservations",
    category: "Réservations",
  },
  {
    action: "confirmerReservation",
    label: "Confirmer une réservation",
    description: "Confirmer une réservation",
    resource: "reservations",
    defaultType: "WRITE",
    route: "/admin/reservations",
    category: "Réservations",
  },
  {
    action: "annulerReservation",
    label: "Annuler une réservation",
    description: "Annuler une réservation",
    resource: "reservations",
    defaultType: "WRITE",
    route: "/admin/reservations",
    category: "Réservations",
  },
  {
    action: "getReservationsStats",
    label: "Statistiques réservations",
    description: "Consulter les statistiques des réservations",
    resource: "reservations",
    defaultType: "READ",
    route: "/admin/reservations",
    category: "Réservations",
  },
];

/**
 * Récupère les actions par catégorie
 */
export function getActionsByCategory(): Record<string, ServerActionConfig[]> {
  const grouped: Record<string, ServerActionConfig[]> = {};
  
  SERVER_ACTIONS_CONFIG.forEach((action) => {
    if (!grouped[action.category]) {
      grouped[action.category] = [];
    }
    grouped[action.category].push(action);
  });
  
  return grouped;
}

/**
 * Récupère une action par son nom
 */
export function getActionByName(actionName: string): ServerActionConfig | undefined {
  return SERVER_ACTIONS_CONFIG.find((action) => action.action === actionName);
}

/**
 * Récupère toutes les catégories uniques
 */
export function getCategories(): string[] {
  const categories = new Set(SERVER_ACTIONS_CONFIG.map((action) => action.category));
  return Array.from(categories).sort();
}
